apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-github-secret
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.gitops.repoURL }}
    targetRevision: {{ .Values.gitops.targetRevision }}
    path: {{ .Values.chartPath }}/arc-github-secret
    helm:
      valuesObject:
        region: {{ .Values.region }}
        appSecretName: {{ .Values.github.appSecretName }}
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-runners
  {{- include "apps.syncPolicy" . | nindent 2 }}
